### ISSUE TITLE
Default location does not work anymore

### ISSUE THREAD

**Issue by nitram2342** [nkl-kst/MMM-RBB-Weather#48]
I use this plugin with default values and the weather report stopped working a few days ago. I think the default value does not exists anymore. If instead another location ID is used as shown via the weather report locations IDs in links on the RBB site, it works again.

**Comment by nkl-kst** [comment]
Thanks for opening this issue. It seems that something changed in the RBB weather data XML. I will try to fix this as soon as possible.

**Comment by nkl-kst** [comment]
I fixed the module, please update it with a `git pull` on your mirror. It should work again now with default configuration.

**Comment by nitram2342** [comment]
Thank you!
