### ISSUE TITLE
Problem displaying data

### ISSUE THREAD

**Issue by nitram2342** [nkl-kst/MMM-RBB-Weather#50]
When I use a non-default id such as 3010387, the widget fails to display data. It shows the temperature, but no wind information. I use updated the MM and the plugin's code today. I attached a picture.

![20201231_180223](https://user-images.githubusercontent.com/152906/103419406-35cf8400-4b93-11eb-8ae1-12b40994681f.jpg)

**Comment by nitram2342** [comment]
The picture is'n the best, but illustrates the problem.

**Comment by nkl-kst** [comment]
Hi Martin,

thanks for opening this issue. This is a result of missing data, see https://www.rbb24.de/include/wetter/data/data_bb_0.xml

```
<city id="3010387" temp="2" dd="-" ffkmh="-" nww="-" wwtext="-" />
```

You could try to use another city ID or to hide the weather text and windspeed informations with config options.

I'm closing this issue for now. Feel free to reopen it if I missed something. Happy new year 🎉

**Comment by nitram2342** [comment]
Okay, that was the missing information, thanks for clarification! I thought it is sufficient, when there is an URL that has the ID such as https://www.rbb24.de/wetter/orte.htm/id=3010387.html and this URL is crawled then. I did not read the source code. Would you mind referencing this XML file in your documentation so that people can look for valid IDs at the correct place? Now I know, but other people may stumble upon this, too.

**Comment by nkl-kst** [comment]
Good idea, thanks. I will put a link to the XML file right after the table for city IDs (https://github.com/nkl-kst/MMM-RBB-Weather#city-ids).
