### ISSUE TITLE
MMM-RBB-weather stops working after MM2 update

### ISSUE THREAD

**Issue by karsc96** [nkl-kst/MMM-RBB-Weather#53]
I am having trouble with the modules since the latest update on MM (2.18.0).
It was succesfully running on (quite) older versions (I have to admit I did not update nor the raspi 3b+ nor MM main for at least 6 months), but stopped after the update.
So I removed the module (npm uninstall, rm -r MMM-RBB...folder) and installed again following instructions mentioned on this page:

> 
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
> npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> 
> added 3 packages from 6 contributors and audited 647 packages in 49.904s
> 
> 1 package is looking for funding
>   run `npm fund` for details
> 
> found 6 vulnerabilities (5 moderate, 1 high)
>   run `npm audit fix` to fix them, or `npm audit` for details

Running MM directly (ignoring messages from installation) with the following settings outputs _undefinded_ on the screen.
Settings in config:

> 
>  {
>                         module: 'MMM-RBB-Weather',
>                         position: "top_right", // All available positions
>                         config: {
>                                 id: "10381",
>                                 days: 4,
>                                 updateinterval: 3600,
>                                 animateCurrentIcon: false,
>                                 animateForecastIcon: false,
>                         }
>                 },

I also noted that the terminal is full of RBB-webpage content, some extract here:

```
> [23.01.2022 16:42.07.979] [WARN]  MMM-RBB-Weather[23.1.2022, 16:42:07]: Error while parsing XML data. XML: "<!DOCTYPE html>
> <!--[if lte IE 8]> <html class="ie8 no-touch" lang="de"> <![endif]-->
> <!--[if IE 9]> <html class="ie9 no-touch" lang="de"> <![endif]-->
> <!--[if (gt IE 9)|!(IE)]><!--> <html class="no-touch" lang="de"> <!--<![endif]-->
> <head>
>  
>  
> <meta charset="utf-8" />
> <title>
> Entschuldigung, es ist ein Fehler aufgetreten  | rbb24</title>
>  
>  
> <meta name="Content-Language" content="de"/>
> <meta http-equiv="Content-Script-Type" content="text/javascript" />
> <meta http-equiv="Content-Style-Type" content="text/css" />
> <meta name="Keywords" content="Radio, rbb, Rundfunk Berlin-Brandenburg"/>
> <meta name="email" content="internet@rbb-online.de"/>
> <meta name="copyright" content="Rundfunk Berlin-Brandenburg, Berlin, Germany"/>
> <meta name="robots" content="index,follow"/>
> 
> <meta name="Description" content="rbb-online bietet aktuelle Informationen und Schwerpunkte aus Berlin und Brandenburg und Informationen zu den Programmen des rbb."/>
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> <meta name="format-detection" content="telephone=no">
> <meta name="application-name" content="rbb24 Website"/>
> <meta name="apple-mobile-web-app-title" content="rbb24 Website">
> <meta name="google-site-verification" content="tsAQnzC2yoGSgn7Tkk-YOncTX_DcwXoEOFGqW9hpqc0">
> <link rel="icon" sizes="192x192" href="/content/dam/rbb/rbb/logos/touch/r24-192.png">
> <link rel="icon" sizes="128x128" href="/content/dam/rbb/rbb/logos/touch/r24-128.png">
> <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/content/dam/rbb/rbb/logos/touch/r24-152.png">
> <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/content/dam/rbb/rbb/logos/touch/r24-76.png">
> <link rel="apple-touch-icon-precomposed" href="/content/dam/rbb/rbb/logos/touch/r24-57.png">
> <meta name="msvalidate.01" content="FAED7252293CB2878BA8E5621A0A9BAB" />
> <link rel="manifest" href="/static/r24/manifest.json">
> <meta name="mobile-web-app-capable" content="yes">
> <meta name="apple-mobile-web-app-capable" content="yes">
> <meta name="msapplication-starturl" content="/index.html">
> <meta name="apple-itunes-app" content="app-id=1071853102"/>
> 
> <!-- rbb24 --> <meta property="fb:pages" content="1645763252367579" />
> <!-- rbb FS --> <meta property="fb:pages" content="138089939576812" />
> <!-- zibb --> <meta property="fb:pages" content="164599463573948" />
> <!-- AS --> <meta property="fb:pages" content="141018599260302" />
> <!-- BA --> <meta property="fb:pages" content="150952781609610" />
> <!-- Ko --> <meta property="fb:pages" content="128969093802560" />
> <!-- rbbspo --> <meta property="fb:pages" content="141926952497345" />
> <!-- kess --> <meta property="fb:pages" content="107794365938898" />
> <!-- thad --> <meta property="fb:pages" content="196521060383505" />
> <!-- sup --> <meta property="fb:pages" content="1860503600868461" />
> <!-- fritz --> <meta property="fb:pages" content="28245726690" />
> <!-- r1 --> <meta property="fb:pages" content="94769185977" />
> <!-- ant --> <meta property="fb:pages" content="612771378929551" />
> <!-- 888 --> <meta property="fb:pages" content="152466181493113" />
> <!-- inf --> <meta property="fb:pages" content="125278414154885" />
> <!-- kul --> <meta property="fb:pages" content="172687819274" />
> 
> <meta name="pocket-site-verification" content="8cef7bc053b8d51de4c633fb42f9c9" />
> 
> <link rel="start" title="Startseite" href="//www.rbb24.de/"/>
> <link rel="search" title="Suche" href="//www.rbb24.de/suche/index.html"/>
> 
> <link rel="copyright" title="Impressum" href="//www.rbb-online.de/impressum/index.html"/>
> <link rel="help" title="Hilfe" href="//www.rbb24.de/hilfe/index.html"/>
> 
> <link rel="SHORTCUT ICON" href="/static/rbb/frontend/favicon.ico"/>
> 
> <meta http-equiv="imagetoolbar" content="no" />
>  
> <link rel="canonical" href="https://www.rbb24.de/error/404.html"/>
> 
> <link rel="image_src" href="https://www.rbb24.de"/>

```
To me it seems the API or website has changed and the module can no longer pull weather data, pulling the complete webpage instead.

Fixing the vulnerabilities from the installation (see below) does not work. It leads to more warnings and error messages and no vulnerabilities fixed.

> 
>                        === npm audit security report ===
> 
> # Run  npm install --save-dev mocha@9.1.4  to resolve 1 vulnerability
> SEMVER WARNING: Recommended action is a potentially breaking change
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │  Inefficient Regular Expression Complexity in                │
> │               │ chalk/ansi-regex                                             │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ ansi-regex                                                   │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ mocha [dev]                                                  │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ mocha > wide-align > string-width > strip-ansi > ansi-regex  │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> 
> # Run  npm install --save-dev spectron@15.0.0  to resolve 4 vulnerabilities
> SEMVER WARNING: Recommended action is a potentially breaking change
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │  Inefficient Regular Expression Complexity in                │
> │               │ chalk/ansi-regex                                             │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ ansi-regex                                                   │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ spectron [dev]                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ spectron > webdriverio > inquirer > strip-ansi > ansi-regex  │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> 
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │  Inefficient Regular Expression Complexity in                │
> │               │ chalk/ansi-regex                                             │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ ansi-regex                                                   │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ spectron [dev]                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ spectron > webdriverio > inquirer > string-width >           │
> │               │ strip-ansi > ansi-regex                                      │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> 
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │ Prototype Pollution in minimist                              │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ minimist                                                     │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ spectron [dev]                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ spectron > webdriverio > optimist > minimist                 │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-vh95-rmgr-6w4m            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> 
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ High          │ Regular Expression Denial of Service in trim-newlines        │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ trim-newlines                                                │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ spectron [dev]                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ spectron > electron-chromedriver > electron-download >       │
> │               │ nugget > pretty-bytes > meow > trim-newlines                 │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-7p7h-4mm5-852v            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 
> 
> ┌──────────────────────────────────────────────────────────────────────────────┐
> │                                Manual Review                                 │
> │            Some vulnerabilities require your attention to resolve            │
> │                                                                              │
> │         Visit https://go.npm.me/audit-guide for additional guidance          │
> └──────────────────────────────────────────────────────────────────────────────┘
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Moderate      │ Exposure of Sensitive Information to an Unauthorized Actor   │
> │               │ in nanoid                                                    │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ nanoid                                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Patched in    │ >=3.1.31                                                     │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ mocha [dev]                                                  │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ mocha > nanoid                                               │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://github.com/advisories/GHSA-qrpm-p2h7-hrv2            │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> found 6 vulnerabilities (5 moderate, 1 high) in 647 scanned packages
>   5 vulnerabilities require semver-major dependency updates.
>   1 vulnerability requires manual review. See the full report for details.

I appreciate your help in advance.
Let me know if you need more data or information.

Many thanks in advance.
karsc

**Comment by nkl-kst** [comment]
Hi karsc,thanks for your detailed informations on this problem, I see "undefined" too since a few days. I share your guess that the API changed and I'll try to investigate it in the next couple of days. Thanks again for your investigation. Nick
