### ISSUE TITLE
Error CSS Stylesheet

### ISSUE THREAD

**Issue by karsc96** [nkl-kst/MMM-RBB-Weather#59]
Apart from the XML-parser problem I am having problems with the css stylesheet.
Since I am not sure if this problem relates to the XML, I am posting this as a separate issue.

In the electron dev log I am getting error messages such as:

> Error on loading stylesheet: modules/MMM-RBB-Weather/font-awesome5.css

<img width="892" alt="Bildschirmfoto 2024-02-02 um 21 38 15" src="https://github.com/nkl-kst/MMM-RBB-Weather/assets/63615603/5821ff7f-89f3-417f-82d2-f4a68f98c5b9">

Appreciate any help.

Raspbian 10 buster
MM 2.26.0
nodejs 18

Thanks in advance.

**Comment by nkl-kst** [comment]
Hi, are your sure this is an error related to the module? It seems that the same error appears for your `css/custom.css`, so the problem is maybe something more general?

**Comment by karsc96** [comment]
No, not completely sure. 
It simply seemed odd to me that the file the module needs (font-awesome5) should be in the module folder but isn't there.
Or does the module refer to the systems CSS files?

**Comment by nkl-kst** [comment]
Have you looked into the module folder to check the file? According to the screenshot, the problem are not missing files, but wrong MIME types.

The module doesn't refer to the system CSS files.

**Comment by karsc96** [comment]
Yes, I checked the module folder, there is no such file (font-awesome5.css):

> xxx@raspberrypi:~/MagicMirror/modules/MMM-RBB-Weather $ ls -al
> insgesamt 600
> drwxr-xr-x   9 pi pi   4096 Feb  5  2022 .
> drwxr-xr-x   7 pi pi   4096 Apr  8  2022 ..
> -rw-r--r--   1 pi pi   2488 Jan 23  2022 CHANGELOG.md
> -rw-r--r--   1 pi pi    724 Jan 23  2022 .eslintrc.json
> drwxr-xr-x   8 pi pi   4096 Feb  2 22:12 .git
> drwxr-xr-x   2 pi pi   4096 Jan 23  2022 .github
> -rw-r--r--   1 pi pi     60 Jan 23  2022 .gitignore
> -rw-r--r--   1 pi pi   3159 Jan 23  2022 IconMapper.js
> -rw-r--r--   1 pi pi   1080 Jan 23  2022 LICENSE.txt
> -rw-r--r--   1 pi pi    679 Jan 23  2022 Logger.js
> -rw-r--r--   1 pi pi   1146 Jan 23  2022 MMM-RBB-Weather.css
> -rw-r--r--   1 pi pi  10284 Jan 23  2022 MMM-RBB-Weather.js
> -rw-r--r--   1 pi pi   5127 Feb  5  2022 node_helper.js
> drwxr-xr-x 465 pi pi  20480 Feb  2 21:03 node_modules
> -rw-r--r--   1 pi pi   1475 Feb  2 20:26 package.json
> -rw-r--r--   1 pi pi 488363 Feb  2 21:03 package-lock.json
> -rw-r--r--   1 pi pi  10189 Jan 23  2022 README.md
> drwxr-xr-x   2 pi pi   4096 Jan 23  2022 templates
> drwxr-xr-x   5 pi pi   4096 Jan 23  2022 test
> drwxr-xr-x   2 pi pi   4096 Jan 23  2022 translations
> -rw-r--r--   1 pi pi    365 Jan 23  2022 .travis.yml
> drwxr-xr-x   3 pi pi   4096 Jan 23  2022 vendor

Here is the error message from electron log, which was pointing me to the missing file.
![error_awesome5](https://github.com/nkl-kst/MMM-RBB-Weather/assets/63615603/34b0f723-b26a-46fd-b20a-99ea72d8b47f)

**Comment by karsc96** [comment]
Any help on this one, please?

**Comment by karsc96** [comment]
Will close this issue now after it started working again.
I reseted (git reset --hard) set nvm explicitly to 18 (nvm use 18) and reinstalled the module. For some reason there were two npm versions installed (18 and 20).
Now it works again.
Thanks anyway for trying to help a bit.
